name: Deploy to GitHub Pages
    on:
      push:
        branches:
          - master
    jobs:
      build-and-deploy:
        runs-on: ubuntu-latest
        
        steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Build
          run: |
            npm install
            npm run build
          env:
            REACT_APP_OPENAI_SECRET: ${{ secrets.REACT_APP_OPENAI_SECRET }}

        - name: Deploy
          run: |
          git config --global user.name "Abe Pena"
          git config --global user.email "pena.abe@gmail.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          npm run deploy